# Site settings
title: Learning Lens 2015
email: laramystara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning Lens 2015 is a conference for homeschool parents in Decorah, Iowa
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://learninglens.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
